DROP TABLE MBLRECIPE;

CREATE TABLE MBLRECIPE(
    MBL_ID NUMBER PRIMARY KEY,
    USERID VARCHAR2(30) NOT NULL,
    NICKNAME VARCHAR2(20) NOT NULL,
    IN_NO VARCHAR2(50) NOT NULL,
    MBL_FILENAME VARCHAR2(200) NOT NULL,
    MBL_CREATEDATE DATE DEFAULT SYSDATE

);

COMMIT;