CREATE TABLE NOTICE(
   NNO NUMBER PRIMARY KEY,
   ID VARCHAR2(30) NOT NULL,
   NTITLE VARCHAR2(100) NOT NULL,
   NCONTENT CLOB NULL,
   NCOUNT NUMBER DEFAULT 0,
   STATUS VARCHAR2(1) DEFAULT 'Y',
   NDATE   DATE DEFAULT SYSDATE,
   MODIFY_DATE DATE DEFAULT SYSDATE
   NICKNAME VARCHAR2(30) NOT NULL -- 추가 -- 
);

CREATE TABLE NOTICECOMMENTS(
    COMMENTS_NO NUMBER PRIMARY KEY,
    COMMENTS_CONTENT CLOB NOT NULL,
    BOARD_NO NUMBER NOT NULL,
    USERID VARCHAR2(30 BYTE) NOT NULL,
    COMMENTS_DATE DATE NOT NULL,
    COMMENTS_STATUS VARCHAR2(20 BYTE) DEFAULT 'Y',
    FOREIGN KEY (USERID) REFERENCES MEMBER(USERID),
    FOREIGN KEY (BOARD_NO) REFERENCES NOTICE(NNO)
);

CREATE SEQUENCE SEQ_COMMENTS_NO;

DROP TABLE NOTICE;
DROP TABLE NOTICECOMMENTS;