<-- notice -->
CREATE TABLE NOTICE 
(
  NNO NUMBER NOT NULL 
, ID VARCHAR2(30 BYTE) NOT NULL 
, NTITLE VARCHAR2(100 BYTE) NOT NULL 
, NCONTENT CLOB 
, NCOUNT NUMBER DEFAULT 0 
, STATUS VARCHAR2(1 BYTE) DEFAULT 'Y' 
, NDATE DATE DEFAULT SYSDATE 
, MODIFY_DATE DATE DEFAULT SYSDATE 
, NICKNAME VARCHAR2(30 BYTE) NOT NULL 
, CONSTRAINT SYS_C007755 PRIMARY KEY 
  (
    NNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C007755 ON NOTICE (NNO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL 
LOB (NCONTENT) STORE AS SYS_LOB0000022382C00004$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
);

COMMENT ON COLUMN NOTICE.NNO IS '게시판번호';

COMMENT ON COLUMN NOTICE.ID IS '아이디';

COMMENT ON COLUMN NOTICE.NTITLE IS '제목';

COMMENT ON COLUMN NOTICE.NCONTENT IS '내용';

COMMENT ON COLUMN NOTICE.NCOUNT IS '조회수';

COMMENT ON COLUMN NOTICE.STATUS IS '게시글 여부';

COMMENT ON COLUMN NOTICE.NDATE IS '작성날짜';

COMMENT ON COLUMN NOTICE.MODIFY_DATE IS '수정날짜';

COMMENT ON COLUMN NOTICE.NICKNAME IS '닉네임';
<-- 끝 -->

CREATE TABLE NOTICECOMMENTS(
    COMMENTS_NO NUMBER PRIMARY KEY,
    COMMENTS_CONTENT CLOB NOT NULL,
    BOARD_NO NUMBER NOT NULL,
    USERID VARCHAR2(30 BYTE) NOT NULL,
    COMMENTS_DATE DATE NOT NULL,
    COMMENTS_STATUS VARCHAR2(20 BYTE) DEFAULT 'Y',
    FOREIGN KEY (USERID) REFERENCES MEMBER(USERID),
    FOREIGN KEY (BOARD_NO) REFERENCES NOTICE(NNO)
);

<-- lbotm -->
CREATE TABLE LBOTM 
(
  BNO NUMBER NOT NULL 
, PT_ID NUMBER 
, USERID VARCHAR2(30 BYTE) 
, B_TITLE VARCHAR2(100 BYTE) 
, B_CONTENT CLOB 
, B_NICKNAME VARCHAR2(30 BYTE) 
, B_CREATEDATE DATE DEFAULT SYSDATE 
, BMODIFYDATE DATE DEFAULT SYSDATE 
, B_COUNT NUMBER DEFAULT 0 
, CT_ID NUMBER 
, B_SRC VARCHAR2(100 BYTE) 
, B_STATUS VARCHAR2(1 BYTE) DEFAULT 'Y' 
, CONSTRAINT SYS_C007724 PRIMARY KEY 
  (
    BNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C007724 ON LBOTM (BNO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL 
LOB (B_CONTENT) STORE AS SYS_LOB0000022366C00005$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
);
<-- 끝 -->



CREATE SEQUENCE SEQ_NNO;
CREATE SEQUENCE SEQ_COMMENTS_NO;
CREATE SEQUENCE SEQ_BNO;

DROP TABLE NOTICE;
DROP TABLE NOTICECOMMENTS;
DROP TABLE LBOTM;