delete from ingredients;

/* 기본 형태 */
/* INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'','',50,500,DEFAULT,DEFAULT,'',''); */

/* 4찬 밥 */

INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'백미','1_밥',50,DEFAULT,DEFAULT,'백미_1.png','백미_1.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'보리밥','1_밥',50,DEFAULT,DEFAULT,'보리밥_1.png','보리밥_1.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'볶음밥','1_밥',50,DEFAULT,DEFAULT,'볶음밥_1.png','볶음밥_1.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'비빔밥','1_밥',50,DEFAULT,DEFAULT,'비빔밥_1.png','비빔밥_1.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'새우볶음밥','1_밥',50,DEFAULT,DEFAULT,'새우볶음밥_1.png','새우볶음밥_1.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'오곡밥','1_밥',50,DEFAULT,DEFAULT,'오곡밥_1.png','오곡밥_1.png');

/* 4찬 서브1 */
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'감자볶음','2_서브1',50,DEFAULT,DEFAULT,'감자볶음_2.png','감자볶음_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'건새우볶음','2_서브1',50,DEFAULT,DEFAULT,'건새우볶음_2.png','건새우볶음_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'고사리나물','2_서브1',50,DEFAULT,DEFAULT,'고사리나물_2.png','고사리나물_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'깻잎나물볶음','2_서브1',50,DEFAULT,DEFAULT,'깻잎나물볶음_2.png','깻잎나물볶음_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'느티버섯','2_서브1',50,DEFAULT,DEFAULT,'느티버섯_2.png','느티버섯_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'도토리묵','2_서브1',50,DEFAULT,DEFAULT,'도토리묵_2.png','도토리묵_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'멸치풋고추볶음','2_서브1',50,DEFAULT,DEFAULT,'멸치풋고추볶음_2.png','멸치풋고추볶음_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'미나리나물','2_서브1',50,DEFAULT,DEFAULT,'미나리나물_2.png','미나리나물_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'소고기메추리알장조림','2_서브1',50,DEFAULT,DEFAULT,'소고기메추리알장조림_2.png','소고기메추리알장조림_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'숙주나물','2_서브1',50,DEFAULT,DEFAULT,'숙주나물_2.png','숙주나물_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'연근조림','2_서브1',50,DEFAULT,DEFAULT,'연근조림_2.png','연근조림_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'콩나물','2_서브1',50,DEFAULT,DEFAULT,'콩나물_2.png','콩나물_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'콩조림','2_서브1',50,DEFAULT,DEFAULT,'콩조림_2.png','콩조림_2.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'파무침','2_서브1',50,DEFAULT,DEFAULT,'파무침_2.png','파무침_2.png');

/* 4찬 서브2 */
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'김치볶음','3_서브2',50,DEFAULT,DEFAULT,'김치볶음_3.png','김치볶음_3.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'깍두기','3_서브2',50,DEFAULT,DEFAULT,'깍두기_3.png','깍두기_3.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'무말랭이무침','3_서브2',50,DEFAULT,DEFAULT,'무말랭이무침_3.png','무말랭이무침_3.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'미역초무침','3_서브2',50,DEFAULT,DEFAULT,'미역초무침_3.png','미역초무침_3.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'배추김치','3_서브2',50,DEFAULT,DEFAULT,'배추김치_3.png','배추김치_3.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'시금치나물','3_서브2',50,DEFAULT,DEFAULT,'시금치나물_3.png','시금치나물_3.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'열무김치','3_서브2',50,DEFAULT,DEFAULT,'열무김치_3.png','열무김치_3.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'오이소박이','3_서브2',50,DEFAULT,DEFAULT,'오이소박이_3.png','오이소박이_3.png');

/* 4찬 메인 */
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'갈치구이','4_메인',50,DEFAULT,DEFAULT,'갈치구이_4.png','갈치구이_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'낙지볶음','4_메인',50,DEFAULT,DEFAULT,'낙지볶음_4.png','낙지볶음_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'닭갈비','4_메인',50,DEFAULT,DEFAULT,'닭갈비_4.png','닭갈비_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'닭강정','4_메인',50,DEFAULT,DEFAULT,'닭강정_4.png','닭강정_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'돈까스','4_메인',50,DEFAULT,DEFAULT,'돈까스_4.png','돈까스_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'돼지갈비','4_메인',50,DEFAULT,DEFAULT,'돼지갈비_4.png','돼지갈비_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'돼지고기볶음','4_메인',50,DEFAULT,DEFAULT,'돼지고기볶음_4.png','돼지고기볶음_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'떡갈비','4_메인',50,DEFAULT,DEFAULT,'떡갈비_4.png','떡갈비_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'매운갈비찜','4_메인',50,DEFAULT,DEFAULT,'매운갈비찜_4.png','매운갈비찜_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'생선까스','4_메인',50,DEFAULT,DEFAULT,'생선까스_4.png','생선까스_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'소불고기','4_메인',50,DEFAULT,DEFAULT,'소불고기_4.png','소불고기_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'소세지볶음','4_메인',50,DEFAULT,DEFAULT,'소세지볶음_4.png','소세지볶음_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'순대볶음','4_메인',50,DEFAULT,DEFAULT,'순대볶음_4.png','순대볶음_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'양념장어구이','4_메인',50,DEFAULT,DEFAULT,'양념장어구이_4.png','양념장어구이_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'작화고등어구이','4_메인',50,DEFAULT,DEFAULT,'작화고등어구이_4.png','작화고등어구이_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'탕수육','4_메인',50,DEFAULT,DEFAULT,'탕수육_4.png','탕수육_4.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'훈제오리','4_메인',50,DEFAULT,DEFAULT,'훈제오리_4.png','훈제오리_4.png');

/* 5찬 밥 */
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'백미','5_밥',50,DEFAULT,DEFAULT,'백미_5.png','백미_5.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'보리밥','5_밥',50,DEFAULT,DEFAULT,'보리밥_5.png','보리밥_5.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'볶음밥','5_밥',50,DEFAULT,DEFAULT,'볶음밥_5.png','볶음밥_5.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'비빔밥','5_밥',50,DEFAULT,DEFAULT,'비빔밥_5.png','비빔밥_5.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'새우볶음밥','5_밥',50,DEFAULT,DEFAULT,'새우볶음밥_5.png','새우볶음밥_5.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'오곡밥','5_밥',50,DEFAULT,DEFAULT,'오곡밥_5.png','오곡밥_5.png');



/* 5찬 메인*/
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'갈치구이','6_메인',50,DEFAULT,DEFAULT,'갈치구이_6.png','갈치구이_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'낙지볶음','6_메인',50,DEFAULT,DEFAULT,'낙지볶음_6.png','낙지볶음_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'닭갈비','6_메인',50,DEFAULT,DEFAULT,'닭갈비_6.png','닭갈비_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'닭강정','6_메인',50,DEFAULT,DEFAULT,'닭강정_6.png','닭강정_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'돈까스','6_메인',50,DEFAULT,DEFAULT,'돈까스_6.png','돈까스_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'돼지갈비','6_메인',50,DEFAULT,DEFAULT,'돼지갈비_6.png','돼지갈비_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'돼지고기볶음','6_메인',50,DEFAULT,DEFAULT,'돼지고기볶음_6.png','돼지고기볶음_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'떡갈비','6_메인',50,DEFAULT,DEFAULT,'떡갈비_6.png','떡갈비_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'매운갈비찜','6_메인',50,DEFAULT,DEFAULT,'매운갈비찜_6.png','매운갈비찜_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'생선까스','6_메인',50,DEFAULT,DEFAULT,'생선까스_6.png','생선까스_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'소불고기','6_메인',50,DEFAULT,DEFAULT,'소불고기_6.png','소불고기_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'소세지볶음','6_메인',50,DEFAULT,DEFAULT,'소세지볶음_6.png','소세지볶음_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'순대볶음','6_메인',50,DEFAULT,DEFAULT,'순대볶음_6.png','순대볶음_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'양념장어구이','6_메인',50,DEFAULT,DEFAULT,'양념장어구이_6.png','양념장어구이_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'작화고등어구이','6_메인',50,DEFAULT,DEFAULT,'작화고등어구이_6.png','작화고등어구이_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'탕수육','6_메인',50,DEFAULT,DEFAULT,'탕수육_6.png','탕수육_6.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'훈제오리','6_메인',50,DEFAULT,DEFAULT,'훈제오리_6.png','훈제오리_6.png');


/* 5찬 서브1 */
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'감자볶음','7_서브1',50,DEFAULT,DEFAULT,'감자볶음_7.png','감자볶음_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'건새우볶음','7_서브1',50,DEFAULT,DEFAULT,'건새우볶음_7.png','건새우볶음_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'고사리나물','7_서브1',50,DEFAULT,DEFAULT,'고사리나물_7.png','고사리나물_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'깻잎나물볶음','7_서브1',50,DEFAULT,DEFAULT,'깻잎나물볶음_7.png','깻잎나물볶음_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'느티버섯','7_서브1',50,DEFAULT,DEFAULT,'느티버섯_7.png','느티버섯_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'도토리묵','7_서브1',50,DEFAULT,DEFAULT,'도토리묵_7.png','도토리묵_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'멸치풋고추볶음','7_서브1',50,DEFAULT,DEFAULT,'멸치풋고추볶음_7.png','멸치풋고추볶음_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'미나리나물','7_서브1',50,DEFAULT,DEFAULT,'미나리나물_7.png','미나리나물_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'소고기메추리알장조림','7_서브1',50,DEFAULT,DEFAULT,'소고기메추리알장조림_7.png','소고기메추리알장조림_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'숙주나물','7_서브1',50,DEFAULT,DEFAULT,'숙주나물_7.png','숙주나물_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'연근조림','7_서브1',50,DEFAULT,DEFAULT,'연근조림_7.png','연근조림_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'콩나물','7_서브1',50,DEFAULT,DEFAULT,'콩나물_7.png','콩나물_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'콩조림','7_서브1',50,DEFAULT,DEFAULT,'콩조림_7.png','콩조림_7.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'파무침','7_서브1',50,DEFAULT,DEFAULT,'파무침_7.png','파무침_7.png');

/* 5찬 서브2 */
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'김치볶음','8_서브2',50,DEFAULT,DEFAULT,'김치볶음_8.png','김치볶음_8.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'깍두기','8_서브2',50,DEFAULT,DEFAULT,'깍두기_8.png','깍두기_8.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'무말랭이무침','8_서브2',50,DEFAULT,DEFAULT,'무말랭이무침_8.png','무말랭이무침_8.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'미역초무침','8_서브2',50,DEFAULT,DEFAULT,'미역초무침_8.png','미역초무침_8.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'배추김치','8_서브2',50,DEFAULT,DEFAULT,'배추김치_8.png','배추김치_8.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'시금치나물','8_서브2',50,DEFAULT,DEFAULT,'시금치나물_8.png','시금치나물_8.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'열무김치','8_서브2',50,DEFAULT,DEFAULT,'열무김치_8.png','열무김치_8.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'오이소박이','8_서브2',50,DEFAULT,DEFAULT,'오이소박이_8.png','오이소박이_8.png');

/* 5찬 수프 */
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'김치국','9_수프',50,DEFAULT,DEFAULT,'김치국_9.png','김치국_9.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'된장국','9_수프',50,DEFAULT,DEFAULT,'된장국_9.png','된장국_9.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'미역국','9_수프',50,DEFAULT,DEFAULT,'미역국_9.png','미역국_9.png');
INSERT INTO INGREDIENTS VALUES(INGREDIENTS_SEQ.NEXTVAL,'콩나물국','9_수프',50,DEFAULT,DEFAULT,'콩나물국_9.png','콩나물국_9.png');

commit;

select count(*) from ingredients;



