drop table PRODUCTREVIEW;

CREATE TABLE PRODUCTREVIEW 
(
  PV_ID NUMBER NOT NULL 
, P_ID NUMBER NOT NULL 
, PV_USER VARCHAR2(30 BYTE) NOT NULL 
, PV_REVIEWCONTENT VARCHAR2(1000 BYTE) NOT NULL 
, PV_CREATEDATE DATE DEFAULT SYSDATE 
, PV_UPDATEDATE DATE DEFAULT SYSDATE 
, STATUS VARCHAR2(1 BYTE) DEFAULT 'Y' 
, PV_PARENT NUMBER 
, CONSTRAINT SYS_C007188 PRIMARY KEY 
  (
    PV_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C007188 ON PRODUCTREVIEW (PV_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE PRODUCTREVIEW
ADD CONSTRAINT SYS_C007295 FOREIGN KEY
(
  P_ID 
)
REFERENCES PRODUCT
(
  P_ID 
)
ENABLE;

COMMENT ON COLUMN PRODUCTREVIEW.PV_ID IS '댓글 글번호';

COMMENT ON COLUMN PRODUCTREVIEW.P_ID IS '게시글( 상품 번호)글번호';

COMMENT ON COLUMN PRODUCTREVIEW.PV_USER IS '작성자';

COMMENT ON COLUMN PRODUCTREVIEW.PV_REVIEWCONTENT IS '내용';

COMMENT ON COLUMN PRODUCTREVIEW.PV_CREATEDATE IS '작성일';

COMMENT ON COLUMN PRODUCTREVIEW.PV_UPDATEDATE IS '수정일';

COMMENT ON COLUMN PRODUCTREVIEW.STATUS IS '삭제여부';

COMMENT ON COLUMN PRODUCTREVIEW.PV_PARENT IS '부모글';

CREATE SEQUENCE pv_id;
CREATE SEQUENCE SEQ_pv_id;

// 상품 문의 게시판CREATE TABLE PRODUCTQNA 
(
  QNA_ID NUMBER NOT NULL 
, QNA_USER VARCHAR2(30 BYTE) 
, QNA_CONTENT CLOB 
, QNA_CREATEDATE VARCHAR2(30 BYTE) 
, P_ID NUMBER NOT NULL 
, QNA_STATUS VARCHAR2(1 BYTE) DEFAULT 'Y' 
, QNA_ANSWER VARCHAR2(1 BYTE) DEFAULT 'N' 
, QNA_SECRET VARCHAR2(1 BYTE) 
, CONSTRAINT SYS_C007457 PRIMARY KEY 
  (
    QNA_ID 
  , P_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C007457 ON PRODUCTQNA (QNA_ID ASC, P_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL 
LOB (QNA_CONTENT) STORE AS SYS_LOB0000021958C00003$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
);

ALTER TABLE PRODUCTQNA
ADD CONSTRAINT SYS_C007195 FOREIGN KEY
(
  P_ID 
)
REFERENCES PRODUCT
(
  P_ID 
)
ENABLE;

COMMENT ON COLUMN PRODUCTQNA.QNA_ID IS '댓글번호';

COMMENT ON COLUMN PRODUCTQNA.QNA_USER IS '글작성자';

COMMENT ON COLUMN PRODUCTQNA.QNA_CONTENT IS '문의 내용';

COMMENT ON COLUMN PRODUCTQNA.QNA_CREATEDATE IS '작성일';

COMMENT ON COLUMN PRODUCTQNA.P_ID IS '게시판번호';

COMMENT ON COLUMN PRODUCTQNA.QNA_STATUS IS '삭제여부';

COMMENT ON COLUMN PRODUCTQNA.QNA_ANSWER IS '답변 여부';

COMMENT ON COLUMN PRODUCTQNA.QNA_SECRET IS '문의 타입';
